### ISSUE TITLE
use case?

### ISSUE THREAD

**Issue by hyusetiawan** [mcollina/fastseries#8]
perhaps showcase more examples? I am interested in using the library because of the performance, my use case is i want to combine a bunch of functions together, a contrived example:
```[toUpperCase, slugify, split]```

Is this the right library to use? Could you provide more explanation on why this is "fast"?  from the explanation is running the  same series multiple times, does not cause memory allocation? I am not sure what that means.

**Comment by mcollina** [comment]
I would not recommend to use this module if you do not understand its usecase. It's probably too advanced.
